## import

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import json

## http request

## store website di variable

In [2]:
website = 'https://books.toscrape.com/'

## get request

In [3]:
response = requests.get(website)

## Status code

In [4]:
response.status_code

200

## soup object

In [5]:
soup = BeautifulSoup(response.content, 'html.parser')

# result

In [6]:
results = soup.find_all('article',{'class' : 'product_pod'})

In [7]:
len(results)

20

## target necessary data

In [ ]:
#Product Title / Name
#Price
#Stock Availability / Status
#Rating (Star Count)
#Detailed Category or URL reference
#Data Cleaning & Transformation: Implem

## Product Title

In [8]:
results[0].find('h3').get_text()

'A Light in the ...'

## Price

In [9]:
results[0].find('p', {'class' : 'price_color'}).get_text()

'£51.77'

## Stock Available

In [10]:
results[0].find('p', {'class' : 'instock availability'}).get_text(strip=True)

'In stock'

## Rating

In [11]:
rating_classes = results[0].find('p', {'class': 'star-rating'}).get('class')
rating = rating_classes[1]
print(rating)

Three

## put everything together inside the loop

In [12]:
title = []
price = []
stock_available = []
rating = []


for result in results :
    # title
    try:
        title.append(result.find('h3').get_text())
    except:
        title.append('n/a')

    #price
    try:
        price.append(result.find('p', {'class' : 'price_color'}).get_text())
    except:
        price.append('n/a')

    #stock_available
    try:
        stock_available.append(result.find('p', {'class' : 'instock availability'}).get_text(strip=True))
    except:
        stock_available.append('n/a')

    #rating
    try:
        rating_text = result.find('p', {'class': 'star-rating'}).get('class')[1]
        mapping = {'One': 1, 'Two': 2, 'Three': 3, 'Four': 4, 'Five': 5}
        rating.append(mapping.get(rating_text, 'n/a'))
    except:
        rating.append('n/a')

In [ ]:
rating


## creatte pandas data frame

In [13]:
book_scrape = pd.DataFrame({'Title' : title, 'Price' : price, 'Stock_Available' : stock_available, 'Rating' : rating})

In [14]:
book_scrape

                                    Title   Price Stock_Available  Rating
0                      A Light in the ...  £51.77        In stock       3
1                      Tipping the Velvet  £53.74        In stock       1
2                              Soumission  £50.10        In stock       1
3                           Sharp Objects  £47.82        In stock       4
4            Sapiens: A Brief History ...  £54.23        In stock       5
5                         The Requiem Red  £22.65        In stock       1
6            The Dirty Little Secrets ...  £33.34        In stock       4
7                 The Coming Woman: A ...  £17.93        In stock       3
8                     The Boys in the ...  £22.60        In stock       4
9                         The Black Maria  £52.15        In stock       1
10  Starving Hearts (Triangular Trade ...  £13.99        In stock       2
11                  Shakespeare's Sonnets  £20.66        In stock       4
12                            Set Me Free  £17.46        In stock       5
13    Scott Pilgrim's Precious Little ...  £52.29        In stock       5
14                      Rip it Up and ...  £35.02        In stock       5
15                  Our Band Could Be ...  £57.25        In stock       3
16                                   Olio  £23.88        In stock       1
17        Mesaerion: The Best Science ...  £37.59        In stock       1
18           Libertarianism for Beginners  £51.33        In stock       2
19                It's Only the Himalayas  £45.17        In stock       2

## Data cleaning

## output in excel (1)

## pagination

In [15]:
title = []
price = []
stock_available = []
rating = []

for i in range (1, 51):
    website = 'https://books.toscrape.com/catalogue/page-' +str(i) + '.html'

    response = requests.get(website)

    soup = BeautifulSoup(response.content, 'html.parser')

    results = soup.find_all('article',{'class' : 'product_pod'})
    
    for result in results :
        # title
        try:
            title.append(result.find('h3').get_text())
        except:
            title.append('n/a')

        #price
        try:
            price.append(result.find('p', {'class' : 'price_color'}).get_text())
        except:
            price.append('n/a')

        #stock_available
        try:
            stock_available.append(result.find('p', {'class' : 'instock availability'}).get_text(strip=True))
        except:
            stock_available.append('n/a')

        #rating
        try:
            rating_text = result.find('p', {'class': 'star-rating'}).get('class')[1]
            mapping = {'One': 1, 'Two': 2, 'Three': 3, 'Four': 4, 'Five': 5}
            rating.append(mapping.get(rating_text, 'n/a'))
        except:
            rating.append('n/a')

In [16]:
book_scrape = pd.DataFrame({'Title' : title, 'Price' : price, 'Stock_Available' : stock_available, 'Rating' : rating})

In [17]:
book_scrape

                                Title   Price Stock_Available  Rating
0                  A Light in the ...  £51.77        In stock       3
1                  Tipping the Velvet  £53.74        In stock       1
2                          Soumission  £50.10        In stock       1
3                       Sharp Objects  £47.82        In stock       4
4        Sapiens: A Brief History ...  £54.23        In stock       5
..                                ...     ...             ...     ...
995  Alice in Wonderland (Alice's ...  £55.53        In stock       1
996    Ajin: Demi-Human, Volume 1 ...  £57.06        In stock       4
997         A Spy's Devotion (The ...  £16.97        In stock       5
998           1st to Die (Women's ...  £53.98        In stock       1
999           1,000 Places to See ...  £26.08        In stock       5

[1000 rows x 4 columns]

In [20]:
##book_scrape.to_excel('book_scrape.xlsx', index=False)
book_scrape.to_excel('data/book_scrape.xlsx', index=False)